name: test1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Icons & UI
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  flutter_staggered_animations: ^1.1.1

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4

  #Mailing and Sharing
  mailer: ^6.0.0
  share_plus: ^7.2.1


  # Notifications
  flutter_local_notifications: ^19.1.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1

  # Storage & Files
  csv: ^5.0.0
  path_provider: ^2.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.1.1

  # HTTP requests (for calling your Node.js server)
  http: ^1.4.0

  # Misc
  url_launcher: ^6.1.10
  android_intent_plus: ^6.0.0
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
